---
kind: pipeline
name: default

steps:
      
- name: Deploy Arachne Production
  image: appleboy/drone-ssh
  settings:
    host: 
      - arachne.servers.tosdr.org
    username:
        from_secret: SSH_USER
    key:
        from_secret: SSH_KEY
    port: 22
    script:
      - service crawler restart
  when:
    event:
    - promote
    - cron
  cron:
  - deploy
  
- name: Deploy Atlas Production
  image: appleboy/drone-ssh
  settings:
    host: 
      - atlas.servers.tosdr.org
    username:
        from_secret: SSH_USER
    key:
        from_secret: SSH_KEY
    port: 22
    script:
      - service crawler restart
  when:
    event:
    - promote
    - cron
  cron:
  - deploy

- name: Deploy AvidReader Production
  image: appleboy/drone-ssh
  settings:
    host: 
      - avidreader.servers.tosdr.org
    username:
        from_secret: SSH_USER
    key:
        from_secret: SSH_KEY
    port: 22
    script:
      - service crawler restart
  when:
    event:
    - promote
    - cron
  cron:
  - deploy
  
- name: Deploy Floppy Production
  image: appleboy/drone-ssh
  settings:
    host: 
      - floppy.servers.tosdr.org
    username:
        from_secret: SSH_USER
    key:
        from_secret: SSH_KEY
    port: 22
    script:
      - service crawler restart
  when:
    event:
    - promote
    - cron
  cron:
  - deploy
  
  
- name: Deploy James Production
  image: appleboy/drone-ssh
  settings:
    host: 
      - floppy.servers.tosdr.org
    username:
        from_secret: SSH_USER
    key:
        from_secret: SSH_KEY
    port: 22
    script:
      - service crawler restart
  when:
    event:
    - promote
    - cron
  cron:
  - deploy
  
  
  
- name: Deploy NosyPeeper Production
  image: appleboy/drone-ssh
  settings:
    host: 
      - nosypeeper.servers.tosdr.org
    username:
        from_secret: SSH_USER
    key:
        from_secret: SSH_KEY
    port: 22
    script:
      - service crawler restart
  when:
    event:
    - promote
    - cron
  cron:
  - deploy
  
  
- name: Deploy Whale Production
  image: appleboy/drone-ssh
  settings:
    host: 
      - whale.servers.tosdr.org
    username:
        from_secret: SSH_USER
    key:
        from_secret: SSH_KEY
    port: 22
    script:
      - service crawler restart
  when:
    event:
    - promote
    - cron
  cron:
  - deploy

- name: Jira Production
  image: plugins/jira
  settings:
    client_id:
      from_secret: jira_client_id
    client_secret:
      from_secret: jira_client_secret
    project: TDC
    instance: tosdr
    environment: production
  when:
    event:
    - promote
    - cron
  cron:
  - deploy
  
---
kind: signature
hmac: bb41e9d4a9bdf6b95197e8d66cfaac4d68039813e6c4d280f98b69c09eac21fe

...
