kind: pipeline
name: default

steps:
      
- name: Deploy Production
  image: appleboy/drone-ssh
  settings:
    host: 
      - arachne.servers.tosdr.org
      - athena.servers.tosdr.org
      - atlas.servers.tosdr.org
      #- avidreader.servers.tosdr.org
      #- floppy.servers.tosdr.org
      #- james.servers.tosdr.org
      #- nosypeeper.servers.tosdr.org
      #- whale.servers.tosdr.org
    username:
        from_secret: SSH_USER
    key:
        from_secret: SSH_KEY
    port: 22
    script:
      - service crawler restart
  when:
    event:
    - promote
    - cron
  cron:
  - deploy

- name: Discord Success Deploy
  image: appleboy/drone-discord
  settings:
    webhook_id:
      from_secret: discord_webhook_id
    webhook_token:
      from_secret: discord_webhook_secret
    message: "Crawlers have been successfully deployed from master branch\n\n{{build.link}}"
  when:
    event:
    - promote
    - cron
  cron:
  - deploy
  
- name: Discord Failure Deploy
  image: appleboy/drone-discord
  settings:
    webhook_id:
      from_secret: discord_webhook_id
    webhook_token:
      from_secret: discord_webhook_secret
    message: "Failed to deploy Crawlers from master branch\n\n{{build.link}}"
  when:
    status:
    - failure
    event:
    - promote
    - cron
  cron:
  - deploy
  
